version: '2'

services:
  elixir:
    build:
      image: perspective/elixir-1.8.1-alpine
      dockerfile: ci/Dockerfile.elixir-1.8.1-alpine

  dockercfg:
    image: codeship/gcr-dockercfg-generator
    add_docker: true
    encrypted_env_file: codeship.aes.google.encrypted
