FROM elixir:1.8.1-alpine

ARG MIX_ENV=test

WORKDIR /opt/app

RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache \
    git \
    build-base \
    inotify-tools

RUN mix local.rebar --force
RUN mix local.hex --force

# This copies our app source code into the build container
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

COPY . .
RUN mix compile
